### PR TITLE
Symfony3 compatibility

### PR DESCRIPTION
**Pull request by iamluc**

### CODE REVIEW

**Comment by NiR-** [comment]
@iamluc please update the `.travis.yml` file in order to test against Symfony 2.x and 3.x.

**Comment by iamluc** [comment]
@NiR- Done. I also added more PHP versions to test.

**Comment by iamluc** [comment]
Mmhh... `symfony/property-access` `3.0` is not installed because others dependencies prevent this.
But tests pass with `"symfony/property-access": "3.0.0 as v2.7.0",` on my machine.

**Comment by Nek-** [comment]
This need to be merged @PedroTroller ! :/

**Pull request merged**
