### PR TITLE
Fix #179

### LINKED ISSUE #179: Symfony2 session // Compatibility with Behat/Symfony2Extension
Hi,

I just discovered this bundle and start to refactor my Behat tests using this one (specially for its fixtures creation, very useful !). But I've just been blocked to a limit: how can I use Symfony2 session (instead of `goutte` for example) in Behat configuration ?

One solution should be to use `Behat\MinkExtension` with `Behat\Symfony2Extension` as following:
```yml
default:
    suites:
        …
    extensions:
        Knp\FriendlyContexts\Extension: ~
        Behat\Symfony2Extension:
            kernel:
                env: "test"
                debug: "true"
        Behat\MinkExtension:
            base_url: "http://example.com/"
            sessions:
                default:
                    symfony2: ~
```

But the problem is that `KnpLabs/FriendlyContexts` bundle is not compatible with `Behat\Symfony2Extension` cause both will boot their own kernel.

To prevent this, it's possible to load `Behat\Symfony2Extension\Context\KernelAwareContext` interface in `Knp\FriendlyContexts\Context\Context`, but I don't find it as a good solution cause it will create a dependency of your bundle to `Behat\Symfony2Extension`.

FYI, you should check [`Behat/Symfony2Extension KernelAwareInitializer`](https://github.com/Behat/Symfony2Extension/blob/master/src/Behat/Symfony2Extension/Context/Initializer/KernelAwareInitializer.php#L56).

### PR DESCRIPTION
**Pull request by vincentchalamon**
Fix #179: allow to combine this bundle with Behat/Symfony2Extension

### CODE REVIEW

**Comment by dunglas** [comment]
:+1:

**Comment by MLKiiwy** [comment]
:+1:

**Comment by guillaumevoisin** [comment]
:+1:

**Comment by vincentchalamon** [comment]
Ping @PedroTroller @iamluc, can somebody review this PR please ? :smile:

**Comment by sagikazarmark** [comment]
Any news?

**Comment by sagikazarmark** [comment]
Ping

**Comment by sagikazarmark** [comment]
Awesome, thanks.

**Pull request merged**
