### PR TITLE
Remove outdated warning

### PR DESCRIPTION
**Pull request by greg0ire**
The commit appears in stable versions of alice

### CODE REVIEW

**Comment by Einenlum** [comment]
It has been included in `nelmio/alice` `2.1`. Maybe it would be better to specify it in the documentation.

**Comment by greg0ire** [comment]
@Einenlum: or maybe require this version of alice with Composer ?

**Comment by greg0ire** [comment]
BTW, this lib requires version alice `~1.0`

**Comment by Einenlum** [comment]
Well I guess we will have to ask @PedroTroller, but I agree that `nelmio/alice ~2.1` should be `required`, or `suggested` if we want the FriendlyContexts to be able to be used without alice (for every contexts except `AliceContext`).

**Comment by greg0ire** [comment]
@PedroTroller , what do you think ? Should the package be suggested (and optionally, an exception be thrown in case the context is used and the library is missing), or should the requirement be changed ? BTW @Einenlum , I don't think the version should be restricted to only `~2.1`. It appears to be compatible with `~1.0` (since this is the currently used requirement), so the new requirement should be something like `~1.7||~2.1` (I don't know if this is the correct syntax).

**Comment by PedroTroller** [comment]
The problem is that the lib is not compatible with Alice 2.0, so it's needs a little refactoring first.

**Comment by greg0ire** [comment]
Ok, so let's stick to ~1.7 for the moment, I'll update my P.R.

**Comment by greg0ire** [comment]
It's ready guys!

**Comment by greg0ire** [comment]
@PedroTroller @Einenlum  It's good to merge, isn't it ?

**Pull request merged**
